In [1]:
!pip install wget | tail -n 1
!pip install scikit-learn | tail -n 1
!pip install "ibm-watson-machine-learning>=1.0.310" | tail -n 1

In [2]:
!pip install boto3 | tail -n 1

In [3]:
# --- 2. Imports ---
import os
import json
import types
import pandas as pd
import numpy as np
from botocore.client import Config
import ibm_boto3
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from ibm_watson_machine_learning.foundation_models.utils.enums import ModelTypes
from ibm_watson_machine_learning.metanames import GenTextParamsMetaNames as GenParams
from ibm_watson_machine_learning.foundation_models import Model

In [4]:
# --- 3. Set up IBM Credentials ---
credentials = {
    "url": "https://us-south.ml.cloud.ibm.com",
    "apikey": input("Enter your IBM API Key: ").strip()
}

Enter your IBM API Key: gvDYe1QWNOVzdxcDn5W7inazV8tXkD5JD2ce6KWdbnDo


In [5]:
project_id = os.environ.get("PROJECT_ID", input("Enter your project_id (or press Enter if none): "))


Enter your project_id (or press Enter if none): 281483ad-0a47-4482-86f4-c610b9535653


In [6]:
# --- 4. Connect to COS & Load Dataset ---
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['apikey'],
    ibm_auth_endpoint='https://iam.cloud.ibm.com/oidc/token',
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.us-south.cloud-object-storage.appdomain.cloud'
)

In [7]:
bucket = input("Enter your COS bucket name: ").strip()
object_key = input("Enter your dataset file name (e.g., legal_sentiment.csv): ").strip()

Enter your COS bucket name: bucket-1pem2ak6shsthrl
Enter your dataset file name (e.g., legal_sentiment.csv): legal_sentiment_dataset (1).csv


In [8]:
body = cos_client.get_object(Bucket=bucket, Key=object_key)['Body']
if not hasattr(body, "_iter_"):
    def _iter_(self): yield from self
    body._iter_ = types.MethodType(_iter_, body)

In [9]:
data = pd.read_csv(body)
data.head()

ID                                         Phrase  Sentiment
0   1          The plaintiff's claims are dismissed.         -1
1   2  The contract is deemed valid and enforceable.          1
2   3     The appeal is denied due to lack of merit.         -1
3   4  The legal team submitted additional evidence.          0
4   5             The appeal is under consideration.          0

In [10]:
# --- 5. Data Cleaning ---
label_map = {-1: 'negative', 0: 'neutral', 1: 'positive'}
data = data.dropna(subset=['Phrase', 'Sentiment'])
data['Sentiment'] = data['Sentiment'].astype(int)
data['Sentiment'] = data['Sentiment'].map(label_map)
print(data['Sentiment'].value_counts())

Sentiment
positive    184
negative    167
neutral     149
Name: count, dtype: int64


In [11]:
# --- 6. Train-Test Split ---
data_train, data_test = train_test_split(data, test_size=0.3, random_state=42, stratify=data['Sentiment'])

In [12]:
# --- 7. Setup IBM Foundation Model ---
parameters = {
    GenParams.DECODING_METHOD: "greedy",
    GenParams.RANDOM_SEED: 42,
    GenParams.REPETITION_PENALTY: 1,
    GenParams.MIN_NEW_TOKENS: 1,
    GenParams.MAX_NEW_TOKENS: 5
}

In [13]:
model = Model(
    model_id=ModelTypes.FLAN_T5_XXL,
    params=parameters,
    credentials=credentials,
    project_id=project_id
)
model.get_details()

/usr/local/lib/python3.11/dist-packages/ibm_watson_machine_learning/foundation_models/utils/utils.py:273: LifecycleWarning: Model 'google/flan-t5-xxl' is in deprecated state from 2025-05-28 until 2025-07-30. IDs of alternative models: None. Further details: https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-model-lifecycle.html?context=wx&audience=wdp
  warnings.warn(default_warning_template.format(


{'model_id': 'google/flan-t5-xxl',
 'label': 'flan-t5-xxl-11b',
 'provider': 'Google',
 'source': 'Hugging Face',
 'functions': [{'id': 'text_generation'}],
 'short_description': 'flan-t5-xxl is an 11 billion parameter model based on the Flan-T5 family.',
 'long_description': 'flan-t5-xxl (11B) is an 11 billion parameter model based on the Flan-T5 family. It is a pretrained T5 - an encoder-decoder model pre-trained on a mixture of supervised / unsupervised tasks converted into a text-to-text format, and fine-tuned on the Fine-tuned Language Net (FLAN) with instructions for better zero-shot and few-shot performance.',
 'terms_url': 'https://huggingface.co/google/flan-t5-xxl/blob/main/README.md',
 'input_tier': 'class_2',
 'output_tier': 'class_2',
 'number_params': '11b',
 'min_shot_size': 0,
 'task_ids': ['question_answering',
  'summarization',
  'retrieval_augmented_generation',
  'classification',
  'generation',
  'extraction'],
 'tasks': [{'id': 'question_answering', 'ratings': {'

In [14]:
# --- 8. Prepare Few-Shot Examples ---
few_shot_examples = []
for sentiment in data_train['Sentiment'].unique():
    samples = data_train[data_train['Sentiment'] == sentiment].sample(2)
    for _, row in samples.iterrows():
        few_shot_examples.append(f"sentence: {row['Phrase']}\nsentiment: {row['Sentiment']}")

few_shot_context = "\n".join(few_shot_examples)

In [15]:
print(few_shot_context)

sentence: The appeal is under consideration.
sentiment: neutral
sentence: The appeal is under consideration.
sentiment: neutral
sentence: The court finds in favor of the plaintiff.
sentiment: positive
sentence: The motion to dismiss is granted.
sentiment: positive
sentence: The defendant is found guilty.
sentiment: negative
sentence: The appeal is denied due to lack of merit.
sentiment: negative


In [16]:
instruction = "Determine the sentiment of the following sentence (as 'positive', 'negative', or 'neutral'). Use the examples below as reference:\n" + few_shot_context + "\n"

# --- 9. Generate Predictions ---
results = []
for text in data_test['Phrase']:
    prompt = instruction + f"\nsentence: {text}\nsentiment:"
    result = model.generate(prompt)['results'][0]['generated_text']
    results.append(result.strip().lower())

In [17]:
# --- 10. Evaluation ---
y_true = data_test['Sentiment'].values
y_pred = results

In [18]:
print("\nClassification Report:")
print(classification_report(y_true, y_pred))


Classification Report:
              precision    recall  f1-score   support

    negative       1.00      1.00      1.00        50
     neutral       1.00      1.00      1.00        45
    positive       1.00      1.00      1.00        55

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150



In [19]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))


Confusion Matrix:
[[50  0  0]
 [ 0 45  0]
 [ 0  0 55]]


In [20]:
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer
# --- Sentiment Distribution ---
sentiment_counts = Counter(y_pred)
total = sum(sentiment_counts.values())
summary_distribution = {sentiment: f"{(count/total)*100:.2f}%" for sentiment, count in sentiment_counts.items()}
print("\nSentiment Distribution (%):")
print(json.dumps(summary_distribution, indent=2))


Sentiment Distribution (%):
{
  "neutral": "30.00%",
  "positive": "36.67%",
  "negative": "33.33%"
}


In [21]:
# --- Top Words/Phrases for Negative Sentences ---
negative_texts = data_test['Phrase'][np.array(y_pred) == 'negative']
vectorizer = CountVectorizer(stop_words='english', ngram_range=(1,2), max_features=10)
X = vectorizer.fit_transform(negative_texts)
top_negative_words = vectorizer.get_feature_names_out()
print("\nTop Words/Phrases in Negative Sentences:")
print(top_negative_words)


Top Words/Phrases in Negative Sentences:
['claims' 'claims dismissed' 'contract' 'contract declared'
 'declared void' 'denied' 'dismissed' 'plaintiff' 'plaintiff claims'
 'void']


In [22]:
# --- Summary Statement ---
majority_sentiment = max(sentiment_counts, key=sentiment_counts.get)
summary_statement = (
    f"The overall sentiment of this document is predominantly\n **{majority_sentiment}** "
    f"({summary_distribution[majority_sentiment]} of sentences).\n "
    f"Frequent negative themes include: {', '.join(top_negative_words)}."
)
print("\nSummary Statement:")
print(summary_statement)


Summary Statement:
The overall sentiment of this document is predominantly
 **positive** (36.67% of sentences).
 Frequent negative themes include: claims, claims dismissed, contract, contract declared, declared void, denied, dismissed, plaintiff, plaintiff claims, void.


In [23]:
# --- 11. Output Results to File ---
output_df = data_test.copy()
output_df['Predicted Sentiment'] = y_pred
output_df.to_csv("legal_sentiment_results.csv", index=False)
print("Results saved to legal_sentiment_results.csv")


Results saved to legal_sentiment_results.csv


In [24]:
# --- 12. Interactive Testing ---
while True:
    custom_input = input("\nEnter a legal sentence to analyze sentiment (or type 'exit'): ").strip()
    if custom_input.lower() == 'exit':
        break
    custom_prompt = instruction + f"\nsentence: {custom_input}\nsentiment:"
    response = model.generate(custom_prompt)['results'][0]['generated_text']
    print(f"Predicted Sentiment: {response.strip().lower()}")


Enter a legal sentence to analyze sentiment (or type 'exit'): the food is very good
Predicted Sentiment: positive

Enter a legal sentence to analyze sentiment (or type 'exit'): the food is good
Predicted Sentiment: positive

Enter a legal sentence to analyze sentiment (or type 'exit'): the food is ok
Predicted Sentiment: neutral

Enter a legal sentence to analyze sentiment (or type 'exit'): the food is bad
Predicted Sentiment: negative

Enter a legal sentence to analyze sentiment (or type 'exit'): exit
